### ISSUE TITLE
Using PoolStringArray for controls vs nodes

### ISSUE THREAD

**Issue by Mainman002** [pigdevstudio/kitchen-tales#51]
I played around with changing things from a Node based signal system to a PoolStringArray. Now I'm not the best at coding but if this could potentially help you out / give you some ideas then that would be cool :) 

so basically my thought is to try and avoid using too many nodes to help remove some overhead wasted logic processes (that being said it probably doesn't free up much if any but it helps keep the Player scene cleaner xD)

![Screenshot_2019-08-16_14-00-06](https://user-images.githubusercontent.com/11281480/63191583-7d9d4c00-c02e-11e9-989a-20fa12e1cdc9.png)

![Screenshot_2019-08-16_14-00-25](https://user-images.githubusercontent.com/11281480/63191586-81c96980-c02e-11e9-9862-d8d99d0f94ee.png)

![Screenshot_2019-08-16_14-03-07](https://user-images.githubusercontent.com/11281480/63191628-96a5fd00-c02e-11e9-8e19-f3e8d998a29f.png)

**Comment by henriiquecampos** [comment]
Thanks a lot for the suggestion! :smiley: 

But there are some issues I see in this approach:

- If you need to communicate inputs to another classes, these classe should be aware of the `PoolStringArray` values and indices as well, which can cause big...troubles if you, e.g., change a value, remove an index...
- It would need some nasty workaround for cases when you want to disable an Action, let's say `dash_p1`, in a scenario where the player is debuffed and can't perform a dash. With nodes you can go with `DashAction.set_process_unhandled_input(false)` and only the dash action will be disabled.  

There are some other thingies, but for the purpose of optimization, Godot is already very optimized to use tons of Nodes, and for the scene cleaning: it totally works! But we are basically moving things from a place to another :stuck_out_tongue: 

Remember: Node's children are basically arrays as well, so instead of having an array on the SceneTree we are having one in the script and inspector :stuck_out_tongue:

The core thing tho is: I'm very glad that it worked for you, and seems like it does the trick for supporting multiplayer! And that's what matters, as long as it works for you.

**Comment by Mainman002** [comment]
ah true, I didn't quite think about upgrades. . . I guess you could redirect these to an onready var Current_Keys = [exported_keys_list] then you can append / remove keyboard keys when you upgrade, but yeah in the end it probably is just changing how you can do things vs optimized. . . Anyway no prob and good luck on your games. keep it up man :)

**Comment by henriiquecampos** [comment]
Thanks, I appreciate a lot the suggestion! Good luck on your games as well, don't hesitate to come back with more interesting approaches!
