### ISSUE TITLE
DashFall and DashJumpFall not properly switching states

### ISSUE THREAD

**Issue by henriiquecampos** [pigdevstudio/kitchen-tales#56]
Something is happening that they are not switching to `Walk` or `Idle` when `Fall`

**Comment by brunosxs** [comment]
I still haven't completely understood the code, but the problem is related to the fact that the y velocity is sometimes kept(maybe related to the slide behavior of godot's kinematic's)
![screen_shot_2019-10-18_16-08-20](https://user-images.githubusercontent.com/1557903/67121628-5dbb0d80-f1c2-11e9-9219-b534243ddf4e.png)

This in turn makes the condition in the fall state to never reach the cancel() method.
I will look at it tomorrow, but we've got a start XD

**Comment by henriiquecampos** [comment]
I think this may have to do with the way `Jump` works, by turning the `SNAP_NORMAL` to `Vector2.ZERO`, so...I think that with that the `KinematicBody2D` doesn't detect that it `is_on_floor` :thinking: 

Btw, good to see you around :blue_heart:
