### ISSUE TITLE
GasCloud triggering HurtBox._on_area_shape_entered

### ISSUE THREAD

**Issue by Raccoon-JS** [pigdevstudio/kitchen-tales#70]
it is located in "**res://actors/combat/HurtBox.gd**"

![OnionHit-error](https://user-images.githubusercontent.com/51072029/68695965-fc454f00-0573-11ea-965f-388c891bcf38.png)

(btw, what does the name Buccerino means?)

**Comment by henriiquecampos** [comment]
Ohh yeah I just fixed it. It is weird because this shouldn't happen, seems like a weird Godot bug, since the GasCloud isn't on any `collision_layer` so...it shouldn't be detectable. But changing its `monitorable` property to `false` fixed this...which is weird.

Also, Buccerino was just a fun pun, "ino" suffix often means "small" in Italian, and "cc" is pronounced as "tch" so...Buccerino = Little/Small Butcher. :stuck_out_tongue:
